package com.converted.cobol;

import java.io.Serializable;

/**
 * Main application service that orchestrates the program flow.
 * This class is the modern, object-oriented equivalent of the
 * PROCEDURE DIVISION's top-level logic for the PreDefMsg program.
 * It follows the DDD-light approach by separating application, domain, and infrastructure concerns.
 *
 * @author Generated by AI Refactoring Expert
 */
public class PredefmsgApplicationService {

    private final MessageService messageService;
    private final ConsoleDisplay consoleDisplay;

    /**
     * Constructs the application service and its dependencies.
     * In a real-world application using a framework like Spring, these dependencies
     * would be injected instead of being instantiated directly.
     */
    public PredefmsgApplicationService() {
        this.messageService = new MessageService();
        this.consoleDisplay = new ConsoleDisplay();
    }

    /**
     * Executes the main logic of the application.
     * This corresponds to the sequence of operations in the PROCEDURE DIVISION.
     * The flow is:
     * 1. Retrieve the predefined message.
     * 2. Display the message.
     */
    public void run() {
        // PROCEDURE DIVISION.
        // This step is analogous to accessing the 'PreDefMsg' variable in WORKING-STORAGE.
        Message messageToDisplay = messageService.getPredefinedMessage();

        // This step corresponds to the 'DISPLAY PreDefMsg' verb.
        consoleDisplay.display(messageToDisplay);

        // The method's completion is analogous to 'STOP RUN'.
    }

    /**
     * The main entry point for the Java application.
     * Its sole responsibility is to instantiate and run the application service,
     * keeping the main method free of business logic.
     *
     * @param args Command line arguments (not used in this conversion).
     */
    public static void main(String[] args) {
        PredefmsgApplicationService app = new PredefmsgApplicationService();
        app.run();
    }
}

/**
 * A Domain Service responsible for business logic related to messages.
 * In this simple case, its responsibility is to know and provide the
 * specific predefined message required by the application.
 */
class MessageService {

    /**
     * Retrieves the predefined message.
     * This logic originates from the VALUE clause of the 'PreDefMsg' data item
     * in the COBOL program's WORKING-STORAGE SECTION.
     * <p>
     * COBOL Source:
     * <pre>
     * 01 PreDefMsg	PIC X(18) VALUE 'Hello again World!'.
     * </pre>
     *
     * @return The predefined {@link Message} object.
     */
    public Message getPredefinedMessage() {
        return new Message("Hello again World!");
    }
}

/**
 * A Value Object representing a message to be displayed.
 * It is implemented as a Java 21 {@code record} for immutability and conciseness.
 * This class models the 'PreDefMsg' data item itself, separating the data
 * from the logic that acts upon it.
 *
 * @param value The string content of the message.
 */
record Message(String value) implements Serializable {}

/**
 * An infrastructure component responsible for handling output to the console.
 * This class encapsulates the technical details of the COBOL 'DISPLAY' verb,
 * isolating I/O operations from the domain and application logic.
 */
class ConsoleDisplay {

    /**
     * Displays the content of a {@link Message} object to the standard output stream.
     *
     * @param message The message to be displayed.
     */
    public void display(Message message) {
        if (message != null && message.value() != null) {
            System.out.println(message.value());
        }
    }
}