classDiagram
%% Diagrama gerado automaticamente pelo agente de conversão COBOL → Java
    class Helloworld <<Entity>>
    class Helloworld {
    }
    class IfExample <<Entity>>
    class IfExample {
    }
    class Increment <<Entity>>
    class Increment {
    }
    class Multip <<Entity>>
    class Multip {
    }
    class NestedIfs <<Entity>>
    class NestedIfs {
    }
    class Performexample <<Entity>>
    class Performexample {
        +String userinitials
        +int a
        +int b
        +int result
        +String formatted
    }
    class Performthroughexample <<Entity>>
    class Performthroughexample {
    }
    class Predefmsg <<Entity>>
    class Predefmsg {
    }
    class Seqfileexample <<Entity>>
    class Seqfileexample {
    }
    class Userinput <<Entity>>
    class Userinput {
    }
